blank_issues_enabled: false
contact_links:
  - name: Documentación del Proyecto
    url: https://github.com/M1keTrike/RealTimeAPP
    about: Consulta el README y la documentación del proyecto antes de abrir un issue.
